### ISSUE TITLE
Support Firefox Account Connection Method

### ISSUE THREAD

**Issue by andrewkrug** [mozilla-iam/person-api#11]
https://github.com/mozilla-iam/person-api/blob/master/person-api/jobs.py#L37
^ This returns the connection method for email addresses in the smart lock.  It will need to support scoring FxA.  However -- we did not really think about what the lock behavior should be when two connection methods are ranked the same.

**Comment by andrewkrug** [comment]
cc/ @gdestuynder for feedback
cc/ @gene1wood for feedback

**Comment by gdestuynder** [comment]
Currently in the rule logic it has an arbitrary order which will match fxa before github, but this might not be ideal. 
The main issue though is email uniqueness. If, for example GitHub == Fxa and both are allowed, the primaryEmail is not useable as an identifier - yet many RP use it as an identifier (and ignore user_id).
I suspect the best trade-off at this time from a technical pov is to continue on the path of providing unique primaryEmail, eventually guarantee it.

On a user point of view though it does mean you cannot interchangeably login with github or fxa when you have the same email behind it.

**Comment by gene1wood** [comment]
> we did not really think about what the lock behavior should be when two connection methods are ranked the same.

If two connection methods provide the same level of good security (e.g. they both provide MFA and report to us if MFA is enabled), they should both be shown in the lock so the user can choose.

We should opt for giving users the most choice in the methods they use to authenticate and limit it *only* if we must because the connection type isn't secure enough.

Another way to look at this is that, once a connection type satisfies our requirements (e.g. reports MFA), it and all of it's peers should be the same level and should all be available to the user.
