### ISSUE TITLE
Fetch my own user info?

### ISSUE THREAD

**Issue by leplatrem** [mozilla-iam/person-api#3]
As far as I understood the person API allows to fetch info about any arbitrary user. And I concede that it requires specific authorizations.

But what if I want to just fetch my own user info? It shouldn't require any specific authorization, no?

That's our usecase with [Doorman](https://github.com/mozilla/doorman/issues/55), where Doorman has no specific client id, it would just forward the JWT token to the Person API and obtain the userinfo for the JWT `subject`.

Is there something I got wrong?

Thanks for your feedback!

**Comment by gdestuynder** [comment]
the application could get the data on behalf of the user through a consent screen (ie there still is an oauth authorization being given, by the user)
i think that would make sense to have

**Comment by leplatrem** [comment]
I don't see how that could work since Doorman has no UI and it's not exposed to the final user

Our use-case is this:

1. Users authenticate from a Web UI (fully static) on Auth0
1. They sent the JWT to a service (RP) as bearer token
1. The service contacts the Doorman as an authorization service (can this user perform this action on this resource?), forwarding the token
1. Doorman looks up info for this user (ie. this JWT subject) and matches authorization policies rules.

Currently *step 4* is done by looking into the JWT payload. But as recommened:

> If you need to query more information about the user, you will need to query the CIS PersonAPI (https://github.com/mozilla-iam/person-api ) which has no such limitations. Please contact us for help utilizing this endpoint.
--

I thought I could just drop replace the JWT payload extraction by a call to a userinfo endpoint. But it seems more complicated than that 😓 

We are only interested in email and groups (especially `hris_staff` by the way, to check whether user is employee)

**Comment by gdestuynder** [comment]
Since you only care about `email` and `groups` you do not actually need to call the PersonAPI (unless Auth0 blocks this for SPA apps for some reason), because they're already in the Auth0 profile.

In other words, when you authenticate the user if you request the scope `openid email profile` (for example) you get a field called `email` and a field called `https://sso.mozilla.com/claim/groups` directly in the `id_token` and in the auth0 userinfo endpoint as well.

Example:
Using https://github.com/auth0-samples/auth0-javascript-samples/01-Login as a base (but it could be a static page - there is no secret data being used here)

Change:
```
diff --git a/01-Login/app.js b/01-Login/app.js
index 8de7793..1273ad9 100644
--- a/01-Login/app.js
+++ b/01-Login/app.js
@@ -10,7 +10,7 @@ window.addEventListener('load', function() {
     redirectUri: AUTH0_CALLBACK_URL,
     audience: 'https://' + AUTH0_DOMAIN + '/userinfo',
     responseType: 'token id_token',
-    scope: 'openid',
+    scope: 'openid email profile',
     leeway: 60
   });

```

In this example local storage will now have an `id_token` ("the jwt") which contains `https://sso.mozilla.com/claim/groups` among other attributes, and an `access_token` which you can also use to query `https://auth.mozilla.auth0.com/userinfo?access_token=xxxxx` (will return the same data)

NOTES: 
1. This will create a consent screen on the user's side the first time, telling the user what data is accessed - if the user consents, the consent (user grant) is saved and remembered by Auth0 so it won't have to ask again.
2. Should you want to use the PersonAPI in the future, you can add it's audience to the request to auth0, and the required scope (say "read:profile") and get back a `token` (access token) and `id_token` ("jwt") which can be used to query the PersonAPI. This is because Auth0 act as an authorizer for PersonAPI.
3. If Doorman in the future presents scoped data that you want other apps to be able to access (ie if you want to pass Doorman authorization data to another app, and have it authorized by Auth0, which, I think would make sense since you then do not need to handle server-to-server credentials and you don't even have to trust the other app, the user can choose), you can also have an Auth0 authorizer for Doorman itself with your own custom scope (so  say when user goes to site "blah", site "blah" would request "additional Doorman authorization data" scope such as `scope: openid email read:doorman_authorizations` and it will get, in exchange, a `token` and `id_token` that can be used to query Doorman for the extra authorization for that user using the same flow.

**Comment by leplatrem** [comment]
Thanks for this super detailed answer :) I'm sorry for the time consuming question, I hope it'll help others too!

I had already some of that running (Auth0 userinfo from SPA, groups from id token, ...) but somehow I thought the Person API would list more groups. 
For instance, in the ID token payload or the Auth0 userinfo, the prefixed groups you showed me once are not listed (eg. mozillians, or the famous `hris_staff` I'm interested about :))

Should I consider they will eventually appear transparently when your final plan is achieved?

Cheers

**Comment by djmitche** [comment]
This sounds very much like the approach that Taskcluster uses: users authenticate to frontend apps (mostly SPAs) and those apps pass audience=login.taskcluster.net.  That causes a one-time consent form during login.  The apps then send the access_token to a [REST API](https://docs.taskcluster.net/reference/integrations/taskcluster-login/references/api#oidcCredentials) which returns corresponding Taskcluster credentials.  I'd be happy to give you a tour of how that works.  Or, depening on the use-case, maybe Doorman can just use Taskcluster credentials?

**Comment by gdestuynder** [comment]
> Should I consider they will eventually appear transparently when your final plan is achieved?

Yes - in fact, if all goes well, they should appear this Thursday

**Comment by leplatrem** [comment]
Thanks for your help! 

Based on your answers, and what I have running, I think I could summarize my issue as:
*where can I get the most detailed user groups list, such as the one that contains prefixed groups like `hris_staff`?*

**Comment by leplatrem** [comment]
I hadn't seen the previous comment. It's all good then! Closing! Thanks for your help and detailed answers!
